# -*- coding: utf-8 -*-
# Deployment settings for /Developer/Marmalade/6.2/quick/target/quick_prebuilt.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['/Developer/Marmalade/6.2/s3e/makefile_builder/mkb.py', '/Users/Sam/Documents/Quick/Projects/Blockenspiel/Blockenspiel.mkb', '--non-interactive', '--no-make', '--no-ide', '--buildenv=WEB', '--builddir', 'build_temp', '--use-prebuilt', '--deploy-only']
mkb = '/Users/Sam/Documents/Quick/Projects/Blockenspiel/Blockenspiel.mkb'
mkf = ['/Developer/Marmalade/6.2/quick/quick_prebuilt.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('/Users/Sam/Documents/Quick/Projects/Blockenspiel/resources', '.', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'Blockenspiel'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'Blockenspiel'
    long_caption = 'Blockenspiel'
    version = [0, 0, 1]
    config = ['/Users/Sam/Documents/Quick/Projects/Blockenspiel/resources/common.icf', '/Users/Sam/Documents/Quick/Projects/Blockenspiel/resources/app.icf']
    data_dir = '/Users/Sam/Documents/Quick/Projects/Blockenspiel/resources'
    iphone_link_lib = ['s3eFacebook', 's3eIOSAppStoreBilling', 's3eIOSGameCenter']
    linux_ext_lib = []
    iphone_link_libdir = ['/Developer/Marmalade/6.2/extensions/s3efacebook/lib/iphone', '/Developer/Marmalade/6.2/extensions/s3eIOSAppStoreBilling/lib/iphone', '/Developer/Marmalade/6.2/extensions/s3eIOSGameCenter/lib/iphone']
    iphone_link_opts = []
    osx_ext_dll = []
    android_external_jars = ['/Developer/Marmalade/6.2/extensions/s3eFacebook/lib/android/s3eFacebook.jar']
    android_external_res = []
    android_supports_gl_texture = []
    android_extra_manifest = []
    iphone_link_libdirs = []
    android_extra_application_manifest = []
    splashscreen_auto_onblack = 1
    win32_ext_dll = []
    android_so = ['/Developer/Marmalade/6.2/extensions/s3eFacebook/lib/android/libs3eFacebook.so']
    iphone_link_libs = []
    target = {
         'x86' : {
                   'debug'   : r'/Developer/Marmalade/6.2/quick/target/quick_prebuilt_d.s86',
                   'release' : r'/Developer/Marmalade/6.2/quick/target/quick_prebuilt.s86',
                 },
         'arm_gcc' : {
                   'debug'   : r'/Developer/Marmalade/6.2/quick/target/quick_prebuilt_d.s3e',
                   'release' : r'/Developer/Marmalade/6.2/quick/target/quick_prebuilt.s3e',
                 },
        }
    assets = assets['Default']

default = DefaultConfig()

######### Configuration: Windows

c = DeployConfig()
config['Windows'] = c
c.os = ['win32']
c.arch = ['x86']
c.target_folder = 'Windows'

######### Configuration: Mac OS X

c = DeployConfig()
config['Mac OS X'] = c
c.os = ['osx']
c.arch = ['x86']
c.target_folder = 'Mac OS X'
